#
# Constants definition
#
# Author: Javier Alcoriza
# Date: October 19th, 2020
#

ST_INIT = 0
ST_WAIT_ONE_MINUTE_01 = 1
ST_READY = 2
ST_READY_HYSTERESIS = 3
ST_TURN_ON_HEATER = 4
ST_TURN_ON_V3V_LIVINGROOM = 5
ST_TURN_ON_V3V_BEDROOM = 6
ST_TURN_ON_V3V_LIVINGROOM_BEDROOM = 7
ST_WAIT_ONE_MINUTE_02 = 8
ST_TURN_ON_PUMP_LIVINGROOM = 9
ST_TURN_ON_PUMP_BEDROOM = 10
ST_TURN_ON_PUMP_LIVINGROOM_BEDROOM = 11
ST_HEATING_LIVINGROOM = 12
ST_HEATING_LIVINGROOM_HYSTERESIS = 13
ST_HEATING_BEDROOM = 14
ST_HEATING_BEDROOM_HYSTERESIS = 15
ST_HEATING_LIVINGROOM_BEDROOM = 16
ST_HEATING_LIVINGROOM_BEDROOM_HYSTERESIS = 17
ST_WAIT_ONE_MINUTE_03 = 18
ST_TURN_OFF_V3V_LIVINGROOM = 19
ST_TURN_OFF_V3V_BEDROOM = 20
ST_TURN_OFF_V3V_LIVINGROOM_BEDROOM = 21
ST_TURN_OFF_PUMP_LIVINGROOM = 22
ST_TURN_OFF_PUMP_BEDROOM = 23
ST_TURN_OFF_PUMP_LIVINGROOM_BEDROOM = 24
ST_TURN_OFF_HEATER = 25


