#
# Constants definition
#
# Author: Javier Alcoriza
# Date: October 19th, 2020
#

ST_INIT = 0
ST_WAIT_ONE_MINUTE_01 = 1
ST_READY = 2
ST_TURN_ON_HEATER = 3
ST_TURN_ON_V3V_LIVINGROOM = 4
ST_TURN_ON_V3V_BEDGROOM = 5
ST_TURN_ON_V3V_LIVINGROOM_BEDROOM = 6
ST_WAIT_ONE_MINUTE_02 = 7
ST_TURN_ON_PUMP_LIVINGROOM = 8
ST_TURN_ON_PUMP_BEDROOM = 9
ST_TURN_ON_PUMP_LIVINGROOM_BEDROOM = 10
ST_HEATING_LIVINGROOM = 11
ST_HEATING_BEDROOM = 12
ST_HEATING_LIVINGROOM_BEDROOM = 13
ST_WAIT_ONE_MINUTE_03 = 14
ST_TURN_OFF_V3V_LIVINGROOM = 15
ST_TURN_OFF_V3V_BEDROOM = 16
ST_TURN_OFF_V3V_LIVINGROOM_BEDROOM = 17
ST_TURN_OFF_PUMP_LIVINGROOM = 18
ST_TURN_OFF_PUMP_BEDROOM = 19
ST_TURN_OFF_PUMP_LIVINGROOM_BEDROOM = 20
ST_TURN_OFF_HEATER = 21


